version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeIC_Automaion0920
  gitServerName: ICAccountTest0920
  gitUrl: https://github.com/MeghaRaj69/EdgeIC_Automaion0920
  gitUsername: MeghaRaj69
  gitToken: edge.scaffolding.EdgeIC_Automaion0920.ICAccountTest0920.gitToken
  gitBranch: Test/CustomBranch/Test
